### PR TITLE
Updated Pause Menu

### PR DESCRIPTION
**Pull request by erokasyuart**
This branch resolves issue #129 with a refined and new sleek look to the pause menu! The pause menu can be opened and closed by pressing the escape key, on top of being able to select the new 'continue' option to return to the game to give the user some flexibility and freedom while playing! The options menu has also been changed to a separate scene as it gets reused more than once, so I thought it would be more efficient to simply use the same scene. There is also a main menu button that takes the player to the main menu before they're able to quit the game! All functional.

### CODE REVIEW

**Comment by PBWiseman** [comment]
Can this please have a proper description for a pull request? With description, link to issues this will resolve, etc

**Review by PBWiseman — CHANGES_REQUESTED** [review]
When you are within interact range of a planet and are in the menu clicking in the menu sends you to the planet and generally hitting Enter ends the game. It seems to not disable keypressing when paused. Also going from the pause menu to the main game screen doesn't unpause the game and the black hole doesn't move. I like the design of the buttons and I love the border design you showed us. Looking forward to seeing that in the game.

**Comment by erokasyuart** [comment]
I added a border as in design mockup # 1 and I would like some feedback for it as I thought the menu looked empty without some kind of box (balance is a design convention!) I also am not sure about the thickness of the box, and also the background. I was thinking about shrinking the dark background to be just for the pause box... Feedback much appreciated...

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
I really like the pause menu, it matches the new look of the main menu and has a great minimalistic design. 

I had issues using the buttons in the pause menu, this is due to the panel being above the buttons in the hierarchy
image
The "GameObject" is being rendered on top of the buttons which causes me to be unable to click them. This could be resolved by  re ordering them or unchecking 'raycast target' on the gameobject inspection panel in the Image component.

Also mentioned in other reviews  is the blackhole not moving when you return to the menu from pause and interacting with planets while the game is paused. 

You also have good comments on your scripts.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
I like the look of the new pause menu border. I think it looks good as is. As mentioned in prior review and in Chases review just issues remaining with clicking buttons, clicking when near planet, and game not unpausing when going to the main menu

**Comment by ChaseBENNC9** [comment]
In PlanetDetection.cs Line 40 add  ` && Time.timeScale != 0` to the if statement

**Review by ChaseBENNC9 — APPROVED** [review]
All concerns addressed. Ready to merge

**Review by PBWiseman — CHANGES_REQUESTED** [review]
All previous bugs fixed however when you pause, open settings, and hit esc, the game resumes but the settings window is still there. Once that is fixed the branch should be all good to merge

**Review by 3MKJOE58 — CHANGES_REQUESTED** [review]
Like the new pause menu design, the game pauses when clicking ECS in the main scene, but when in the planet scene when pressing ECS the game doesn't pause and won't show the pause menu.

**Review by PBWiseman — APPROVED** [review]

**Pull request merged**
