### PR TITLE
More planet visuals

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

Adding more planets from [this pack](https://assetstore.unity.com/packages/3d/environments/sci-fi/planets-26903) to the project

## Issue number and link

#109 #107 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have written any applicable tests
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by PBWiseman** [comment]
I have added the planets and I have made the textures apply to the planet scene. Ready for review.

**Review by ChaseBENNC9 — APPROVED** [review]
New Planets look great and appear in both scenes. The Folders are sorted and easy to navigate and I like the fact that the names still appear on the HUD with no issues. I am happy with this

**Review by erokasyuart — APPROVED** [review]
Looks very nice with unique planets and shapes! Brings more variety into the game and feels more like planets than spheres!

**Review by 3MKJOE58 — APPROVED** [review]
Looks very nice, amazing new planet textures.

**Pull request merged**
