### PR TITLE
Title Screen Rework

### PR DESCRIPTION
**Pull request by erokasyuart**
Full GUI title "menu" screen has been reworked:
- A new scene called "Title Screen" has been added with no changes made to the old scene.
- Title screen scene uses the black hole prefab with the growing script removed.
- From feedback, the most favourable text position was from concept 4, so if you're happy with that or like to see what the other concepts look like now with the real background, please let it be known.
- Changed font to a thin, and sleek modern style.
- Buttons have a dark transparent background when hovered.
- Reuses the old menu management script.
- There is also a settings menu, with controls and credits tabs all in one scene!

Further ideas:
- Doing the keybinds/settings menu as well as the pause menu?
- I also still want to do the occasional flying animal.
- How is the scale of the black hole? I've made it scaled small as aesthetically possible and close to the GUI before it phases through the canvas.

### CODE REVIEW

**Review by 3MKJOE58 — COMMENTED** [review]
Like the new title screen, alot better and more realistic then the old one and the controls display is very nice, and nice addition of the blackhole.

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
the menu looks really good. I really like the new Font and the black hole background. 
As mentioned the options button causes a null exception error. It is caused by `settings.SetActive(false);` but this line still seems to work properly so I'm not really sure what the problem is.

Code looks good no issues there. 
New options menu also looks good however the text can be quite difficult to read especially the camera and escape
image

Same thing in the other menu, 
- not sure how you've done it but could moving the blackhole left slightly work? or is it the same blackhole in the menu screen?

Also who is Chase Benn**i**tt-Hill? My last name is Bennett-Hill... with an e... just saying
image

**Review by PBWiseman — CHANGES_REQUESTED** [review]
The design looks very sleek! Love it overall. Just a couple of minor requests.

The MenuManager script is currently attached to both the MenuManager object as well as the ButtonController object in TitleParent. This is causing the start to run twice and I believe is the source of the null reference issue.

Previous reviews have already noted that the name of one of your coworkers is currently incorrect.

I like the addition of extra tabs on the menu. Will be very handy when we have a proper settings section and the transition is nice. Can the title of the tab be changed to Credits? Also the jobs should possibly either be removed or expanded upon? I am doubtful most people would know what a TL or CI is, though they would be more likely to understand QA.

The effect when you click the tab buttons is great. Looks very smooth. Should/can there be any indication of which tab you are currently on?

I agree with the other review that the black hole directly behind the settings is distracting. My idea, and this may be too complex for the sprint time remaining, is to have the camera smoothly pan to the right a little to more the black hole further to the left of the screen when you open the settings and then move back when you exit it?

The only other thing is that the in game menu and settings buttons still point to the old menu. I know the pause menu is going to be changed soon but it should have a temp fix.

Once again I just want to say that I love the overall design of the menu! It looks super slick and modern.

**Comment by PBWiseman** [comment]
Just adding on to the review that the scaling seems broken when you increase or reduce resolution. 

image
16:10

image
4K UHD

**Review by ChaseBENNC9 — APPROVED** [review]
Glad to see my name has been fixed - obviously the most **important**  game breaking bug.
Options menu is now much easier to read with the opaque background. And the issue regarding the null exception error has been resolved. There is still an issue with the different screen sizes which I don't think is too important at this point and it could be resolved in a later sprint. I am happy for your feature to be merged

**Review by PBWiseman — CHANGES_REQUESTED** [review]
I love the new shading. The only issue is that it is slightly off center for me.
Both the section buttons
image
image
As well as the hovering effect on the keybinds
image

This is using the Full HD screen size so it's not a weird scaling thing either.

Also the back button on the settings menu seems to no longer work?

Couple of other issues for a later sprint are that the in game pause menu shows the old settings page and there is no Tutorial button. As long as both are added to issues backlog this should be all good. The tutorial is probably for the best since it is out of date at the moment. We can fix it when the new planet gameplay is added.

**Review by PBWiseman — APPROVED** [review]
All concerns addressed. Happy to merge. Excellent work.

**Review by ChaseBENNC9 — APPROVED** [review]

**Pull request merged**
