### PR TITLE
Reworking keybindings

### PR DESCRIPTION
**Pull request by PBWiseman**
The controls at the moment are confusing and it is easy to get them mistaken and lose progress. I will be changing these around to keys that make more sense.

There is also the issue of keybindings being all over the place in different scripts. I will be combining these into a single shared script to make it easier to change later.

### CODE REVIEW

**Review by 3MKJOE58 — COMMENTED** [review]
Like the new key bindings

**Review by ChaseBENNC9 — APPROVED** [review]
New Key binds are all working. The new script is formatted nicely and I like that you have included the header comment. 

I did notice that when you are close to a planet you can click while looking anywhere. 
I think this could be a separate issue. because I may be able to solve it with my ray-cast code with the new HUD. 

Didn't notice any issues while in the build and no errors.

**Comment by PBWiseman** [comment]
Going to delay merging this until after the title screen branch is merged as I will need to apply a few of the changes to that as well

**Review by erokasyuart — APPROVED** [review]
This is more conventional I am a fan!

**Comment by PBWiseman** [comment]
Fixed some merging issues. Should be all good to merge

**Review by erokasyuart — APPROVED** [review]

**Review by ChaseBENNC9 — APPROVED** [review]

**Pull request merged**
