### PR TITLE
Better gravity

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

This pull request is responding to the feedback from our lecturer that our gravity should feel more threatening early and mid game but still possible (but difficult) to escape late game.

## Issue number and link

#176 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have written any applicable tests
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by PBWiseman** [comment]
Merged work from #211 into this as some of those changes will affect this branch.

**Comment by PBWiseman** [comment]
Changed the gravity values and size. Can I get some feedback on how it feels now so I can continue to tweak it.

**Review by erokasyuart — CHANGES_REQUESTED** [review]
I think the ranges of the inner, middle, and outer gravities are a reasonable size. I changed the inner player gravity to 1 and it was much more noticeable but still easy to boost out of when too close. I also changed the middle gravity to 0.2. These made the game just a little more thrilling but not frustrating or difficult.

**Review by ChaseBENNC9 — APPROVED** [review]
I like the feel of the new gravity changes. and when it is combined with the growth rate of the blackhole I think it will give player's a more challenging experience in later game while not being impossible.

**Comment by PBWiseman** [comment]
I have increased the values of all four black hole gravity values. I also moved the player a little bit further away, so they don't get pulled into the stronger gravity wells too quickly.

**Review by ChaseBENNC9 — APPROVED** [review]
I like the feel of the new values, and they should work well with the black hole growth

**Review by 3MKJOE58 — APPROVED** [review]
Like the feel of the new gravity.

**Review by erokasyuart — APPROVED** [review]

**Pull request merged**
