### PR TITLE
V1.9.0

### PR DESCRIPTION
**Pull request by PBWiseman**
Changelog
-
- The Ship Boost has been Increased 
- Planet Orbit Speed has been decreased
- Can now tell how many animals remain on a planet
- Support added for entering and leaving a planet multiple times

Bug fixes
-
- Fixed clipping end game text 
- Button text is now centered in all menus

Known bugs
- 
- Small lag spike on first time looking at a planet
- Planets just behind player jitter slightly when boosting
- Planets orbit can make it pass through the player
- On planet gameplay has incorrect textures compared to the planet you land on in space
- Animals can rarely phase through the planet
- Trees can rarely hover slightly above the planet

Background Improvements
-
- Improved GitHub issue templates 
- Build time reduced

### CODE REVIEW

**Review by erokasyuart — APPROVED** [review]
No errors and everything works as intended very lovely and good happy to approve!

**Review by ChaseBENNC9 — APPROVED** [review]
No errors found , everything is working as expected 
happy to merge

**Review by 3MKJOE58 — APPROVED** [review]
Everything works, good to merge.

**Comment by PBWiseman** [comment]
All working. Good to merge

**Comment by PBWiseman** [comment]
Actually I need to add the known bugs to the patch notes and add the readme hang on

**Pull request merged**
