### PR TITLE
Space Info Panel

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
## Describe your changes

This branch is going to update the Space Info panel to include details about which animals are available on each planet before the player actually lands on it.  

## Issue number and link

#206 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have written any applicable tests
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Review by PBWiseman — CHANGES_REQUESTED** [review]
There is a missing space after the names and : of neutral and scared animals. It currently only deletes the lines for each animal species after all animals are rescued. Should it delete the line individually for each species as you save it? Is the font size of the animal details being smaller intentional?

Beyond those I like the changes. The animal names seem a little bit odd and not space themed but I think it's fine. Out of scope for this branch

**Comment by ChaseBENNC9** [comment]
> There is a missing space after the names and : of neutral and scared animals. It currently only deletes the lines for each animal species after all animals are rescued. Should it delete the line individually for each species as you save it? Is the font size of the animal details being smaller intentional?
> 
> Beyond those I like the changes. The animal names seem a little bit odd and not space themed but I think it's fine. Out of scope for this branch

I did originally have the text smaller because i was thinking of it being subtext. Yeah i can change it to hide for each animal i just didn't know how it would look with space between each line. I could generate some sci-fi sounding species and see how it looks. worth a look into anyway

**Comment by PBWiseman** [comment]
> > There is a missing space after the names and : of neutral and scared animals. It currently only deletes the lines for each animal species after all animals are rescued. Should it delete the line individually for each species as you save it? Is the font size of the animal details being smaller intentional?
> > 
> > Beyond those I like the changes. The animal names seem a little bit odd and not space themed but I think it's fine. Out of scope for this branch
> 
> I did originally have the text smaller because i was thinking of it being subtext. Yeah i can change it to hide for each animal i just didn't know how it would look with space between each line. I could generate some sci-fi sounding species and see how it looks. worth a look into anyway

My thought was that the lines would move upwards instead of having blank spaces

**Comment by ChaseBENNC9** [comment]
- [] Fixed issue with colon
- [] Each animal line disappears when all collected and moves up
- [] More alien - like name varients

**Review by PBWiseman — APPROVED** [review]
Well done! All of my issues have been addressed. I love the new names. Happy for this to be merged

**Review by erokasyuart — CHANGES_REQUESTED** [review]
I like the names, they fit the planet names in Yousef's branch--very futuristic.

An issue I have is that they're a bit redundant. As a player, I don't know what a "Grogan" is compared to a "Tomois", but when I get on the planet, I know that the snake is hostile but the deer is not. You mentioned that there's not a lot of space on the panel now, so I think you should give them some different colours to _show_ the player that there's hostiles, neutral, and scared animals on a planet.

**Review by 3MKJOE58 — APPROVED** [review]
Like the new names, approved to merge.

**Review by erokasyuart — APPROVED** [review]
Much better. Issues addressed.

**Pull request merged**
