### PR TITLE
V1.8.0

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
Changelog
-
- New End Menu Screen
- Scared animal added
- Hostile animal now chases and attacks
- New planet textures added

Bug fixes
-
- 16:10 aspect ratio fixed for menu's 
- Fixed errors when going to the main menu from a planet

Known bugs
- 
- Small lag spike on first time looking at a planet
- Planets just behind player jitter slightly when boosting
- Planets orbit can make it pass through the player
- On planet gameplay has incorrect textures compared to the planet you land on in space
- Animals can rarely phase through the planet
- Trees can rarely hover slightly above the planet

Background Improvements
-
- Implemented Unity Testing Framework for bug testing 
- Added Whitespace Validation workflow

### CODE REVIEW

**Review by erokasyuart — APPROVED** [review]
- On the planet, the score still says "temp score display"
- Hostile animal is too fast!
- Floating tree on planet

**Review by 3MKJOE58 — APPROVED** [review]
Game runs well, no bugs were found during testing.

Happy to merge to main.

**Comment by PBWiseman** [comment]
> * On the planet, the score still says "temp score display"
> * Hostile animal is too fast!
> * Floating tree on planet

Speed changed! The other two are issues for next sprint

**Review by PBWiseman — APPROVED** [review]

**Comment by ChaseBENNC9** [comment]
There was an issue where the hostile animal can immediately kill the player when you land on the planet.  Which i have added to the issues list. Other than that looks good to merge

**Pull request merged**
