### PR TITLE
Adding game icon

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

Adding an icon for our game. This will be used for the .exe file and when in the taskbar

## Issue number and link

#194 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have written any applicable tests
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by PBWiseman** [comment]
Added an icon to the game files and to the readme. Would love feedback on how people like it. The icon shows up both on the .exe and in the task bar when the game is open. You need to build it in a new folder so the cache doesn't use the old icon

**Review by 3MKJOE58 — APPROVED** [review]
Like the game icon,

**Review by ChaseBENNC9 — APPROVED** [review]
New Logo looks great. Build loaded it up ok and it displays correctly at different sizes on desktop,, file explorer and on taskbar. approved to merge

**Review by erokasyuart — APPROVED** [review]
Swagalicious!

**Pull request merged**
