### PR TITLE
Main HUD

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
The main goal of this branch is to update the main HUD to be more consistent with the new Planet Pop-up displays
This has Requested by the product owner.  This will solve issue #135 
**Sprint Goals:**
- [x]  Current Speed of the ship

 - [x] Directional gimble (Reworking the Arrow / tick)

- [x]  How far away from the black hole you are (Completed in previous sprint)

 - [x] Can also have alarms blaring when you get too close to the black hole (Text warnings rework)

**Delayed for the next sprint:**
 - Rework the side planet display into the HUD

### CODE REVIEW

**Comment by ChaseBENNC9** [comment]
## Current Progress:
New Arrow Indicator system that points to the planets at the edge of the screen and changes to a target when the player looks closely enough: assets imported from ""
#### The Arrows can point towards:
- The closest planet with a blue arrow 
- any planets that are in 'danger' shown with a red arrow

**Note:**  Not currently optimized for 16:10 ratio

Speed Indicator: May need reworking to get the values right but for now it gets the forces acting on the player and converts it to a value using the 'magnitude' of the vectors

Warning Alert: the screen flashes red. I made it quite slow but enough to show its a bad thing but don't want it to be too fast either. There's also a new message on the screen with symbols and a red font

Side Planets: Not sure if We actually need them anymore. But for now they act the same and disappear when they're destroyed or rescued

**Comment by ChaseBENNC9** [comment]
Should now work with 16:10 ratio

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Love the new UI elements. The arrow and the target look great. The speed display looks good but possibly higher numbers would feel better like you said. The full energy bars need to be readded to the script to have the boost duration show on the ship. I like the warning for being too close to the black hole but the red is a little intense at the moment. Maybe needs to be slightly toned down. Or maybe have it focused to the edges of the screen so the middle is more clear where you are looking? Good work in general though. Looks a lot better

**Comment by PBWiseman** [comment]
Also there are still a number of debug statements that should be removed in the end version

**Review by PBWiseman — APPROVED** [review]
All previous issues sorted.  I know you've said you are unsure about the new boost indicator but I quite like it. Maybe with an additional visual to indicate that is it the boost duration. If you, and other reviewers, are set against it then that's fine but I wouldn't even mind removing the on ship fuel indicators in favour of this.

**Review by erokasyuart — CHANGES_REQUESTED** [review]
The speed could definitely use a bigger number so it seems like it's going fast!

I was also a little confused when I started the game because I wasn't sure what that number was supposed to indicate. I see that it's changing, but it could've been my distance to the planet or the planet to the black hole... It's very vague. I think adding a small unit type in the corner would be helpful to the player for context!

Also, the arrow warning is still there :)

**Review by 3MKJOE58 — APPROVED** [review]
Like the new HUD, the speed indicator is a nice addition, and the new planet-locking system is nice when pointing at a planet the arrow stays there and when looking the other way an arrow will appear.

**Review by erokasyuart — APPROVED** [review]
Much better with a higher number and units very good job!

**Pull request merged**
