### PR TITLE
Fixing Build and Caching workflows

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
## Describe your changes

I will be attempting to find the solution to the broken workflows due to the runner being out of space

## Issue number and link

#202 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have written any applicable tests
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by ChaseBENNC9** [comment]
Cache job seems to run properly now. Can't really predict if. the build and release job is fixed until we merge. 
I don't fully know what caused the issue, but I found an article somewhere that suggested adding a line that apparently clears unused files from the runner.  
## If you want to see it working, 
you can see successful runs [here](https://github.com/BIT-Studio-3/Space-Rescue/actions/runs/6514184933/job/17695019173)

## Extra Info
If you're interested about the disk usage issues. I found that our build takes a lot more space on the disk than expected. 
- Have a look at the Checking disk space steps. and look at the usage in /dev/root.
- Here is the disk usage before the build started (26GB)
image
- and this is the space we have after building the game (9.3GB)
image

**Review by PBWiseman — APPROVED** [review]
Looks like it is working to me!

**Review by 3MKJOE58 — APPROVED** [review]
Working for me, good to merge.

**Review by erokasyuart — APPROVED** [review]
Caching makes me go, "Ca-ching!"

**Pull request merged**
