### PR TITLE
Models

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
## Describe your changes

This is going to add full models to the planet scene, (the animals, the player and foliage) if I have time I am also planning on introducing a way of dynamically sending different animals to different planets randomly and looking into a way to show this on the UI.

## Issue number and link

#106 #108 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have written any applicable tests (not applicable)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by ChaseBENNC9** [comment]
Issue: Models are randomly selected every time the player enters a planet even on the same planet.

**Comment by ChaseBENNC9** [comment]
> **Issue:** Models are randomly selected every time the player enters a planet even on the same planet.

Resolved by moving the Assignment of models to the Planet Info script

**Comment by ChaseBENNC9** [comment]
- [ ] Animal Models
- [ ] Animal Animated
- [ ] Tree Models
- [ ] Player Model
- [ ] Player Animated

**Review by erokasyuart — APPROVED** [review]
Looks really good! Although during my play testing I could walk inside the drop ship if I was only slightly off the ground (by walking over an animal). The player model might be just tall enough to do this, maybe we could fix the drop ship collision?

**Review by PBWiseman — APPROVED** [review]
I'll give it a more thorough test for bugs when it's ready for final review but I love what you've done. The models all look awesome. The animal animations are well implimented. The player model looks really good. Animations for capturing an animal and for getting attacked will be needed but they will probably need code changes as well. Very happy with how the game looks with this.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Love the new models and amazing work on getting all the animations and the code working.
Noticed there is this error when I launched. Unsure if harmless or not?
image

I also did notice that the death animation plays when leaving the planet vis the dropship,

**Comment by ChaseBENNC9** [comment]
> Love the new models and amazing work on getting all the animations and the code working. Noticed there is this error when I launched. Unsure if harmless or not? image
> 
> I also did notice that the death animation plays when leaving the planet vis the dropship,

I will have a look at the animation the error is talking about and see how to fix it. but i think it might be harmless, not sure.
and yeah makes sense that the death animation plays when leaving now that  I think about it. I will see if i can find a solution for that

**Comment by ChaseBENNC9** [comment]
**Known Issue:** Player can still move after the death animation is played and override the  animation until the main scene loads

**Review by PBWiseman — APPROVED** [review]

**Review by 3MKJOE58 — APPROVED** [review]
Love the new animal and player animations, models, good death animation for player, approved for merge.

**Pull request merged**
