### PR TITLE
On planet rotation

### PR DESCRIPTION
**Pull request by 3MKJOE58**
Adding on planet rotation

### CODE REVIEW

**Comment by PBWiseman** [comment]
Any updates on this branch? Will it be ready for review this weekend?

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
### Code:  ✅
Scripts have comments that explain the code. 
Variable names follow guidelines. 
### Functionality 
It is possible to rotate the camera while right clicking. which seems to work ok currently but I have a couple suggestions to possibly improve this.
### Improvements 
- Currently the mouse rotates only up and down. I think the feature would work better if there was more control over rotating. Not sure how it would be implemented currently though. 
- Also the camera jolts to look at the sky when you first right click, and then you can rotate down towards the planet but also more up and towards nothing. Is it possible to make the camera start at the current angle and have a slightly reduced limit so you can just look where the planet is?
- The original request from Adon was to have the planet gameplay feel similar to the space gameplay. My interpretation of this would be that the camera kind of orbits the planet. and the player follows this positioning. This may be a very complicated feature and I may have seen it differently to others, so I don't mind if others disagree with this point. 
## Other Notes 
- You have two scripts: `planetMaterialManager.cs` and `ApplyMaterial.cs` in this branch which From what I understand this would solve the issue of the planet textures carrying through. However I cannot see if these have been implemented yet. Is this still a Work in Progress at this point?

**Comment by 3MKJOE58** [comment]
> ### Code: ✅
> Scripts have comments that explain the code. Variable names follow guidelines.
> 
> ### Functionality
> It is possible to rotate the camera while right clicking. which seems to work ok currently but I have a couple suggestions to possibly improve this.
> 
> ### Improvements
> * Currently the mouse rotates only up and down. I think the feature would work better if there was more control over rotating. Not sure how it would be implemented currently though.
> * Also the camera jolts to look at the sky when you first right click, and then you can rotate down towards the planet but also more up and towards nothing. Is it possible to make the camera start at the current angle and have a slightly reduced limit so you can just look where the planet is?
> * The original request from Adon was to have the planet gameplay feel similar to the space gameplay. My interpretation of this would be that the camera kind of orbits the planet. and the player follows this positioning. This may be a very complicated feature and I may have seen it differently to others, so I don't mind if others disagree with this point.
> 
> ## Other Notes
> * You have two scripts: `planetMaterialManager.cs` and `ApplyMaterial.cs` in this branch which From what I understand this would solve the issue of the planet textures carrying through. However I cannot see if these have been implemented yet. Is this still a Work in Progress at this point?

they are scripts from former branch, forgot to delete them before pushing.

**Review by erokasyuart — CHANGES_REQUESTED** [review]
There is some good commenting going on and very easy to understand code.

However, there are some issues:
- I'd like for the camera rotation to be automatic, it's very annoying to have to hold down the right mouse button to look
- There's no horizontal/dynamic camera movement
- When you click the right mouse button, it resets to 0,0 on start (according to palin) so it makes the player look to the sky
- It's too zoomed in-- although if the camera was pushed a bit behind the player to see the horizon roll over I think that would be cool, or just return to the normal top-down camera view.
- The camera rotates too far down and up and needs a smaller cap.
- If the camera is moved up too far then the player model becomes unseen
- The player rotation is good it's just that it doesn't match the camera rotation

I don't think this is ready to be merged this sprint, and I think this could have potential if we were at this point earlier in the sprint so these issues could be addressed and fixed sooner.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
I like the basis of the work however there are still issues with it and due to how late in the sprint it was submitted there isn't really enough time to properly review and fix it. The horizontal movement is good. The biggest issue is the camera instantly snapping to looking directly up at the sky. There could be a cap on how far the camera can move but once we have things in the skybox like the black hole or the planets then looking fully up could be useful and interesting.
For horizontal camera movement either the player should stay still and the camera should tilt to the side, or the player should rotate with the camera direction. Having no camera movement and with player rotation looks odd.
Finally the zoom seems to have been increased? Was this intentional?
I think at the moment unfortunantly this isn't ready to merge and we need to get the sprint done and the build made.

**Comment by PBWiseman** [comment]
I had a look through the branch. I like the changes to controlling it and clamping the rotation. Definitely improved. I did notice that it's possible to rotate the camera while paused which just needs an if timescale is 0 check. The camera also snaps up and then back down when you spawn in. The player rotating with the mouse moving side to side also doesn't seem to do anything since the rotation changes whenever you move in a direction anyway. Also, the camera still feels closer than it was, but I am unsure if that is just a placebo.

Would it be possible to basically copy the X camera movement to the Y movement to have a full range of camera freedom? Or does that not work?

Good changes overall! Feels much better!

**Comment by 3MKJOE58** [comment]
> I had a look through the branch. I like the changes to controlling it and clamping the rotation. Definitely improved. I did notice that it's possible to rotate the camera while paused which just needs an if timescale is 0 check. The camera also snaps up and then back down when you spawn in. The player rotating with the mouse moving side to side also doesn't seem to do anything since the rotation changes whenever you move in a direction anyway. Also, the camera still feels closer than it was, but I am unsure if that is just a placebo.
> 
> Would it be possible to basically copy the X camera movement to the Y movement to have a full range of camera freedom? Or does that not work?
> 
> Good changes overall! Feels much better!

Have tried that before and it didn't work, it wont apply.

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
### Code:  ✅
Scripts have comments that explain the code. 
Variable names follow guidelines. 
### Functionality ✅
- Rotation feels smoother overall and is a great improvement from last time
- Unused files have been deleted  
### Bugs
- When you move the camera with the mouse when the player is standing still the player model spins 
- 
image

### Other 
- ~~Not sure if it's just my computer but the fonts for the pause menu seem to be broken.~~  
- Can be ignored as font file does not exist
image

**Review by ChaseBENNC9 — APPROVED** [review]
Player flipping fixed
Font in pause menu fixed

**Review by PBWiseman — APPROVED** [review]
All concerns addressed. Happy for this to be merged

**Review by erokasyuart — APPROVED** [review]
All concerns addressed happy to merge.

**Pull request merged**
