### PR TITLE
The HUD

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
This Branch is going to merge the planet tracker and side planet display into one HUD. The Intention is to have a menu appear when the player is looking at a planet. This Menu is going to have all the information displayed such as the Planet Name, distance from the planet , the planet distance from the black hole, Whether it has been rescued and if the player can land on it.

Later on the types of animals available on the planet can also be shown here. 

The Side planet display has been reworked to no longer have icons and they now disappear from the side once rescued or destroyed. 

In order to tell when the planet is currently looked at by the player I have started refactoring FindingPlanets.cs
the arrow still tracks the closest planet but I have also added a raycast that starts from the center of the screen and returns information about an object that was hit. I believe this to be a much more efficient method. At this point the only objects that the raycast will return are those with the Planet tag this is to avoid it hitting the player's ship or the black hole.  

To Do List (Sprint 1)
- [x] Check that Everything is functioning in the build
- [x] Remove Unused variables and methods 
- [x]  Black hole distance for planets 
- [x] Black Hole info panel 
- [x] Comments on Ray Casting

### CODE REVIEW

**Comment by ChaseBENNC9** [comment]
Started testing a new raycast where planets find their distance to the blackhole. Need to trial some changes in order to get the distance of the destroy Collider not the warning area. Seems this has something to do with layers need to do some research

**Comment by ChaseBENNC9** [comment]
Added a layer mask so the raycast hits the distortion hitbox. It returns a length which can be an estimate distance from a planet to the black hole. There are three different "levels" or colors for the text. 
- Normal (Blue) Normal color means the planet is relativiely safe from the black hole at this point
- Orange: The Planet is within the warning sphere. still time to rescue
- Red: About half way -> extreme danger 3/4 into the warning sphere. est 150 units from hitbox

**Comment by ChaseBENNC9** [comment]
Added a panel for the black hole that shows approx distance, number seems to be accurate based on planet distances but it changes quite quickly when mouse moves.

**Comment by ChaseBENNC9** [comment]
Re worked the distances so one ray cast tests when the player is looking at a target and the other gets the distance between the player and the hit object.  This has removed the issue of changing the distance when moving the look slightly and made the distances seem more realistic in comparison.

**Review by 3MKJOE58 — CHANGES_REQUESTED** [review]
The new HUD is a lot better the old one, just want to suggest a few changes, the circle in the middle for pointing maybe a little smaller so it doesn't interact with the ship, and the panel if you could bring it a little down i think it will make it look better
Capture

**Review by PBWiseman — CHANGES_REQUESTED** [review]
The post processing effects from getting too close to the black hole are gone. Not totally sure the of the cause?

After rescuing a planet it still shows up as "Ready to Land". It does say that the planet has been rescued but keeping the landing text there given you can't actually land there again feels odd.

As for the general design I like it but it feels like it takes up a lot of the screen space? Especially when in full screen mode. Could the info panel be a bit smaller?

The circle in the middle looks good. Possibly also a touch large but I'm not sure about that? I think eventually having it be a little animated would look amazing but that's well out of scope. Should the + in the middle be removed since we have the circle now? Might make it look a bit cleaner.

Do you intend to keep the arrow and tick mark? Does the planet info screen show enough information? Or I guess this could be added to the middle in a later sprint with a small ring around it pointing to the closest? Unsure.

Very impressive coding overall. The functionality is great. The only other thing is just to check over the added files for unneeded ones to keep the game size as low as possibly

**Comment by PBWiseman** [comment]
Another thing I just noticed is that the game UI now breaks again on any aspect ratio other than full HD. 
image
image

**Comment by ChaseBENNC9** [comment]
> The post processing effects from getting too close to the black hole are gone. Not totally sure the of the cause?
> 
> After rescuing a planet it still shows up as "Ready to Land". It does say that the planet has been rescued but keeping the landing text there given you can't actually land there again feels odd.
> 
> As for the general design I like it but it feels like it takes up a lot of the screen space? Especially when in full screen mode. Could the info panel be a bit smaller?
> 
> The circle in the middle looks good. Possibly also a touch large but I'm not sure about that? I think eventually having it be a little animated would look amazing but that's well out of scope. Should the + in the middle be removed since we have the circle now? Might make it look a bit cleaner.
> 
> Do you intend to keep the arrow and tick mark? Does the planet info screen show enough information? Or I guess this could be added to the middle in a later sprint with a small ring around it pointing to the closest? Unsure.
> 
> Very impressive coding overall. The functionality is great. The only other thing is just to check over the added files for unneeded ones to keep the game size as low as possibly

I believe I know what broke the distortion effect, I will undo what I did and try find another solution.
I will make the circle slightly smaller as that has been mentioned already, 
I think the arrow should have its own focus as there's other elements that need to be factored in too. 
I have removed all the files I don't need and I will change the ready to land on the panel as well.
I will also try and fix the UI scaling not sure what happened there and I will make the panel smaller

**Comment by ChaseBENNC9** [comment]
> Another thing I just noticed is that the game UI now breaks again on any aspect ratio other than full HD. image image

Is this when you play the game or in the editor? my script from last semester scales stuff once the game starts

**Comment by ChaseBENNC9** [comment]
image
image

**Comment by PBWiseman** [comment]
My bad. Tested it some more and the scaling is still fine. The only other thing is that on lower resolutions the panel is noticeably very fuzzy. Obviously just a side effect of lower pixel count but is there any way to scale it so it looks a little better? 
image

**Review by erokasyuart — CHANGES_REQUESTED** [review]
I still think the crosshair is a little too big, could you please make it a fraction smaller?

I'm not sure what the cause or solution is, but sometimes the HUD won't show up when the crosshair is over a planet, whether it's far away or close. Often I've seen this happen to planets that are intersecting the black hole, and upon further testing, I do believe that to be the case! Which is very obnoxious when the planet is clearly in view. I'm also not sure if it would make sense if you could detect a planet that is directly behind the centre of the black hole, realistically I would feel like it would have some distortion (metaphorically, not an actual mechanic), but from seeing the planet behind/in the outer parts of the black hole, I'd like for the HUD to show up.

I think it would be good to have how many animals saved for the planet, just so the player can keep track! Maybe in the future we could have the native species listed on there as well!

This is probably for another issue but I want to write it down anyway because it's somewhat related, but I was keeping an eye on the closest planet to the black hole and watching the black hole distance number tick down, and it started to speed up, (even though I'm pretty sure the growth of the black hole remains at a constant rate), and the planet was nowhere near close to the black hole delete trigger area! When the number went down to 0... It went back to 400ish units! Then like I mentioned previously about the raycast, I couldn't see the HUD easily anymore but within about a second of seeing the distance go back to 400, it got deleted! Before the HUD disappeared, the units were dropping at about half a second each, so I doubt it suddenly shot back down to 0.
image
Here's an example of this - was looking at the closest planet to the black hole and got deleted at 464. There was also another planet (it's seen in this screenshot currently getting sucked) that was stuck at a distance of 600. 

image
Seems like when the planets spawn too close, they disregard the colour change.

Also I tested it again, and the HUD disappears even when the planets aren't intersecting the blackhole. Maybe the black hole was invisibly disrupting the raycast, but I had to fly really close to see it again, and I was just staying still watching it when it suddenly disappeared!

Best to see if you can recreate these yourself to see what I'm talking about, but I'm happy to recreate it for you at some point.

**Comment by ChaseBENNC9** [comment]
> I still think the crosshair is a little too big, could you please make it a fraction smaller?
> 
> I'm not sure what the cause or solution is, but sometimes the HUD won't show up when the crosshair is over a planet, whether it's far away or close. Often I've seen this happen to planets that are intersecting the black hole, and upon further testing, I do believe that to be the case! Which is very obnoxious when the planet is clearly in view. I'm also not sure if it would make sense if you could detect a planet that is directly behind the centre of the black hole, realistically I would feel like it would have some distortion (metaphorically, not an actual mechanic), but from seeing the planet behind/in the outer parts of the black hole, I'd like for the HUD to show up.
> 
> I think it would be good to have how many animals saved for the planet, just so the player can keep track! Maybe in the future we could have the native species listed on there as well!
> 
> This is probably for another issue but I want to write it down anyway because it's somewhat related, but I was keeping an eye on the closest planet to the black hole and watching the black hole distance number tick down, and it started to speed up, (even though I'm pretty sure the growth of the black hole remains at a constant rate), and the planet was nowhere near close to the black hole delete trigger area! When the number went down to 0... It went back to 400ish units! Then like I mentioned previously about the raycast, I couldn't see the HUD easily anymore but within about a second of seeing the distance go back to 400, it got deleted! Before the HUD disappeared, the units were dropping at about half a second each, so I doubt it suddenly shot back down to 0.
> image
> Here's an example of this - was looking at the closest planet to the black hole and got deleted at 464. There was also another planet (it's seen in this screenshot currently getting sucked) that was stuck at a distance of 600. 
> 
> image
> Seems like when the planets spawn too close, they disregard the colour change.
> 
> Also I tested it again, and the HUD disappears even when the planets aren't intersecting the blackhole. Maybe the black hole was invisibly disrupting the raycast, but I had to fly really close to see it again, and I was just staying still watching it when it suddenly disappeared!
> 
> Best to see if you can recreate these yourself to see what I'm talking about, but I'm happy to recreate it for you at some point.

Yeah ray casts have turned out to be a major pain. The ray is likely hitting the black hole first and causing those issues. I will try and re create it

Not sure why the counter would reset like that I will have a look at that.

I purposely left out the animal information for now because of the rework going into the planets currently there will likely be a change to how points work and just thought it was far down the line. 

I will shrink the circle again

**Comment by erokasyuart** [comment]
> > I still think the crosshair is a little too big, could you please make it a fraction smaller?
> > I'm not sure what the cause or solution is, but sometimes the HUD won't show up when the crosshair is over a planet, whether it's far away or close. Often I've seen this happen to planets that are intersecting the black hole, and upon further testing, I do believe that to be the case! Which is very obnoxious when the planet is clearly in view. I'm also not sure if it would make sense if you could detect a planet that is directly behind the centre of the black hole, realistically I would feel like it would have some distortion (metaphorically, not an actual mechanic), but from seeing the planet behind/in the outer parts of the black hole, I'd like for the HUD to show up.
> > I think it would be good to have how many animals saved for the planet, just so the player can keep track! Maybe in the future we could have the native species listed on there as well!
> > This is probably for another issue but I want to write it down anyway because it's somewhat related, but I was keeping an eye on the closest planet to the black hole and watching the black hole distance number tick down, and it started to speed up, (even though I'm pretty sure the growth of the black hole remains at a constant rate), and the planet was nowhere near close to the black hole delete trigger area! When the number went down to 0... It went back to 400ish units! Then like I mentioned previously about the raycast, I couldn't see the HUD easily anymore but within about a second of seeing the distance go back to 400, it got deleted! Before the HUD disappeared, the units were dropping at about half a second each, so I doubt it suddenly shot back down to 0.
> > image
> > Here's an example of this - was looking at the closest planet to the black hole and got deleted at 464. There was also another planet (it's seen in this screenshot currently getting sucked) that was stuck at a distance of 600.
> > image
> > Seems like when the planets spawn too close, they disregard the colour change.
> > Also I tested it again, and the HUD disappears even when the planets aren't intersecting the blackhole. Maybe the black hole was invisibly disrupting the raycast, but I had to fly really close to see it again, and I was just staying still watching it when it suddenly disappeared!
> > Best to see if you can recreate these yourself to see what I'm talking about, but I'm happy to recreate it for you at some point.
> 
> Yeah ray casts have turned out to be a major pain. The ray is likely hitting the black hole first and causing those issues. I will try and re create it
> 
> Not sure why the counter would reset like that I will have a look at that.
> 
> I purposely left out the animal information for now because of the rework going into the planets currently there will likely be a change to how points work and just thought it was far down the line.
> 
> I will shrink the circle again

For the animals that's so true!

**Comment by ChaseBENNC9** [comment]
https://forum.unity.com/threads/having-issues-with-raycasts-reporting-incorrect-distances.142955/ 
https://stackoverflow.com/questions/63634733/avoid-raycast-hitting-player-without-layermask
For future reference

**Comment by ChaseBENNC9** [comment]
### Changes
- [x] Addressed post processing issue 
- [x] Reduced size of new crosshair circle 
- [x] Reduced size of panel and moved it down slightly
- [x] Addressed black hole interfering with planet ray-casts   
### Outstanding 
- There is still a weird issue where the distance can reach 0 and then it jumps back to a different number. I believe this could be solved with the new collisions in the gravity feature. 
- Distances are better but the ray is still fired from the center of the planet not an edge, which seems to cause some inconsistencies 
- It is likely some of the functionality of this will break because of changes to the blackhole , I will look into the feature so it is easier to fix this after merging.

**Review by PBWiseman — APPROVED** [review]
All concerns from prior review addressed. Good to merge

**Review by erokasyuart — APPROVED** [review]
image
There's still some issue with the distance of the planet before being sucked in but hopefully this can be fixed later on :)

**Pull request merged**
