### PR TITLE
Planet Saved States

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

In this branch I will be working out how to have saved and consistent states for the planets so you can know what is on them from space, and so you can enter and leave the planet as often as you want.

## Issue number and link

#168 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added any applicable tests
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by PBWiseman** [comment]
Note: This is failing the tests due to an outage with github actions

**Comment by PBWiseman** [comment]
The coding is done for the moment until after review. I still need to write tests for this so I am not marking it as ready for review quite yet, but I would still like some feedback on the gameplay. The animals for each planet should be determined when the main scene opens and persist, and update, no matter how many times you enter and leave the planet. You can see how many animals are left when you look at a planet.

**Review by 3MKJOE58 — COMMENTED** [review]
Checked the gameplay and planets have the same number of animals that is displayed.

**Review by ChaseBENNC9 — APPROVED** [review]
### Code:  ✅
All the scripts have clear comments that explain the code. 
Variable names follow guidelines. 
### Functionality ✅
Functions as expected. I can travel to each planet and the animal counter updates to the amount of the animals remaining on the planet.  No errors while testing. Everything works properly in the editor and in the build of the game. 

### Tests ✅
Your tests both pass when running inside the test runner. No issues there
#### Bugs
Noticed earlier in the week. The UI takes a second to update to the newest number of animals. At this point it is barely noticeable and I don't think it is a major thing at the moment.
 But I will make a note of it so it can be put into issues later if needed.

**Review by erokasyuart — CHANGES_REQUESTED** [review]
Great! It works as expected with the number of animals saved being unique to each planet works well. I also like that when there are remaining animals on a planet the text is red. Good and understandable commenting too.

### Bugs
When the player looks at a planet and enters then leaves the planet, the numbers of remaining animals don't update until after the player looks away and back at the planet for the panel to refresh.

### Improvements
When all the animals on a planet are saved, I think it's redundant to say "Animals remaining: 0" instead I think it should be renamed to something like "Planet Rescued" or "Planet X Saved" or something along the lines of that, like the past versions. Also keep the green it works great.

**Comment by PBWiseman** [comment]
> ### Improvements
> When all the animals on a planet are saved, I think it's redundant to say "Animals remaining: 0" instead I think it should be renamed to something like "Planet Rescued" or "Planet X Saved" or something along the lines of that, like the past versions. Also keep the green it works great.

Addressed

**Review by 3MKJOE58 — APPROVED** [review]
Great it works very well, With the number of animals displayed for each planet and how many are there, the player also is able to return to the planet and rescue the remaining animals even when rejected by the hostile animal, happy to merge.

**Review by erokasyuart — APPROVED** [review]
Issues addressed! Well done.

**Pull request merged**
