### PR TITLE
Planet UI

### PR DESCRIPTION
**Pull request by erokasyuart**
## Describe your changes

Hey what's up you guys, in this sprint's pull request we're updating the UI on the planet to include the species caught and how many of them were caught, the planet name, and the black hole distance. There is an issue with the UI that the black hole distance sits on as it doesn't seem to be affected by the canvas' automatic adjusting.

You can find the changes in the "Planet UI" scene.

Some feedback I'd like for the design are:
- The position of the panel
- Currently it's just text for the animals caught, but I considered using little images of the animals and numbers to visually show what animal has been caught

## Issue number and link

#148 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by PBWiseman** [comment]
Any updates on this branch? Will it be ready for review this weekend?

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
### Code:  ✅
All the scripts have clear comments that explain the code. 
Variable names follow guidelines. 
### Functionality ✅
The UI updates correctly for each animal and displays the correct number as expected.
### Improvements 
As you pointed out the temp score display is not needed anymore due to the updated display but maybe including a total in your new display could be useful. 
### Errors
There are some errors due to the scene not having a pause menu object and also not being able to leave but I think these will be solved once everything is moved back into the original planet scene

**Review by PBWiseman — CHANGES_REQUESTED** [review]
The UI looks consistent to the planet one and fits in well. Couple of small issues and it should be good to merge.
Currently there is a null reference exception if the pause menu isn't first turned on before playing. The UI currently makes no distinction between animals caught and animals deposited. It would also be nice to have the current total score not just the score for this planet. Finally it doesn't have the list of remaining animals but I have just noticed this never made it into the issue so it can go to another sprint.

**Review by 3MKJOE58 — CHANGES_REQUESTED** [review]
The UI looks good and fits with the rest of the game IU, but there is an error with the object reference.

**Review by ChaseBENNC9 — APPROVED** [review]
**Addressed Requested changes:** ✅
Pause Menu now works within scene and no longer gives errors.  

We agreed to keep the temp score in the scene until a work around is found 
approved to merge

**Review by PBWiseman — APPROVED** [review]
Not all requested features have been implemented and you will need to work on it for the next sprint as well however what is there is functional. This is acceptable to merge.

**Review by 3MKJOE58 — APPROVED** [review]
Good to merge

**Pull request merged**
