### PR TITLE
V1.7.0

### PR DESCRIPTION
**Pull request by PBWiseman**
Changelog
-
- Planets orbit independently
- Planet spawns standardized to a more realistic planetary system
  * Planets now can have orbital inclination
- Added a speed indicator 
- New warning system 
- New planet tracking Indicators
- On planet gameplay rework
   * Trees
   * Hostile animal (Chase + Attack not yet implemented)
   * Pathfinding and movement smoothed
   * Dropship to deposit animals in and escape from
   * Minigame removed
   * Further changes coming next patch
   * All planet visuals WiP
 - Updated visuals for pause menu
 - Pause menu added while on planet

Bug fixes
-
- Planets no longer spawn collided with other planets
- Planets no longer spawn within the black hole
- Player turning on planet enabled
- Lag spike on first time looking at a planet reduced but not eliminated
- End screen menu button working

Known bugs
- 
- Scaling issues on 16:10 monitors
- Small lag spike on first time looking at a planet
- Planets just behind player jitter slightly when boosting

Background / Documentation Improvements
-
- New readme on GitHub
- GitHub issue templates added
- GitHub pull request templates added

### CODE REVIEW

**Comment by PBWiseman** [comment]
Note to check before merging with main: Are all menu, pause, and end game buttons working, are all the correct branches in the build settings, and are all scene transitions pointing to the correct scene

**Review by 3MKJOE58 — COMMENTED** [review]
the game plays well, except when on the planet tying find animals, I remember that pressing ENTER will allow the player to exit and continue roaming, but when i press ENTER the game closes and shows the end screen.

**Comment by PBWiseman** [comment]
> the game plays well, except when on the planet tying find animals, I remember that pressing ENTER will allow the player to exit and continue roaming, but when i press ENTER the game closes and shows the end screen.

Being fixed at the moment

**Comment by PBWiseman** [comment]
> the game plays well, except when on the planet tying find animals, I remember that pressing ENTER will allow the player to exit and continue roaming, but when i press ENTER the game closes and shows the end screen.

Should be fixed

**Review by PBWiseman — COMMENTED** [review]
All working. Cannot find any bugs.

**Review by erokasyuart — APPROVED** [review]

**Review by 3MKJOE58 — APPROVED** [review]
works fine. good for merge no bugs found.

**Review by ChaseBENNC9 — APPROVED** [review]

**Pull request merged**
