### PR TITLE
Planet gameplay rework

### PR DESCRIPTION
**Pull request by PBWiseman**
This branch is to rework the general planet gameplay. Starting out with a broad scope. I am going to get an overall design and actually added the various features will likely take a few sprints. Major points that the Product Owner asked us to focus on are as follows:
There should be time pressure while in the planet. Either from seeing the black hole expanding towards the planet or through whatever the on planet activity is. Need to change the whole planet experience. Remove the minigame. The general feel should be more arcade-y. A possible idea is to have the planet be a sort of maze with obstacles that can hinder or kill you, enemies wandering around, and having to collect the animals to bring them back to the ship. Possibly include some sort of platforming section.
Currently this is fixing #116 #110

### CODE REVIEW

**Comment by PBWiseman** [comment]
Bit of scoping notes. The on planet visuals are being completed in another branch with the general planet visuals. Going to leave the player and animal models for the moment and just focus on the gameplay. Any platforming section will also be for later as it is extremely difficult to have a good jumping mechanic and this will need focus on its own.

**Comment by PBWiseman** [comment]
Reverted several failed commits

**Comment by PBWiseman** [comment]
Fix for on planet turning has been added to this as part of changing the movement.

**Comment by PBWiseman** [comment]
Update: Movement working much smoother. Instead of checking if it's exactly at the target pos it checks if its close enough. I also removed the radius buffer on movement. I kept it on spawning but I also had it send a raycast into the planet so it will instantly snap to the surface. Movement for both the player and the animals also now have collision detection in front of them and they will refuse to move into obstacles. The spawning script can be reused for whatever you want to spawn. It currently spawns animals and trees.

**Comment by PBWiseman** [comment]
Added second hostile animal. The idea is that if they see you they will pursue and try to damage you (or insta kill? Unsure). To rescue them you need to approach from behind and save them before they turn around. Still a WIP

**Comment by PBWiseman** [comment]
Having issues with the player detection so I am moving to working on a new section of the gameplay rework. Imported a basic dropship. No I don't like the model either. It's the best free one I could quickly find. Ill change it later. The idea is that you will now go and grab the animals and bring them back to the dropship to rescue them and then when you need to leave the planet you will do it from the dropship.

**Comment by PBWiseman** [comment]
Got colliders working better. After testing a few things decided to just go with a number display that shows how many animals you are holding atm. Will be changed later I just want to get it working first.

**Comment by PBWiseman** [comment]
Branch ready for review. Added a score display. You now need to get to the dropship to deposit animals or escape. A lot of this is temporary to get it working and will be improved upon in the next script. Some of the stuff that will be for next script is as follows:
Score visuals
Held animals visuals
Hostile animal will pursue and attack you if it sees you
There will be a scared animal that will run if it sees you
More stuff on the planet to avoid/interact with

**Comment by PBWiseman** [comment]
> I like the new gameplay improvements. The new spawning system is great and will definitely be helpful when we introduce dynamic animals later on. I think the temp ui is fine for now it gets the job done. Nice comments in your code and introduction to the new comment headers.
> 
> Also Question: Is the hostile detection supposed to make the animal move towards you or just show the alert symbol? I understand it's still a WIp so just wanted to check
> 
> other than that everything is looking great so far

I had a lot of trouble with the hostile detection system so I decided I needed a full sprint to get it feeling satisfying. Currently it only detects and doesn't lock on or chase you

**Comment by ChaseBENNC9** [comment]
> > I like the new gameplay improvements. The new spawning system is great and will definitely be helpful when we introduce dynamic animals later on. I think the temp ui is fine for now it gets the job done. Nice comments in your code and introduction to the new comment headers.
> > Also Question: Is the hostile detection supposed to make the animal move towards you or just show the alert symbol? I understand it's still a WIp so just wanted to check
> > other than that everything is looking great so far
> 
> I had a lot of trouble with the hostile detection system so I decided I needed a full sprint to get it feeling satisfying. Currently it only detects and doesn't lock on or chase you

Understandable, In that case I will approve it

**Review by ChaseBENNC9 — APPROVED** [review]

**Review by 3MKJOE58 — APPROVED** [review]
Like the new game and spawning of the animals, and like the spawning of trees.

**Review by erokasyuart — APPROVED** [review]

**Pull request merged**
