### PR TITLE
Gravity

### PR DESCRIPTION
**Pull request by PBWiseman**
I will be adding gravity systems. Both from the black hole pulling the player in whenever they get too close as well as the planets orbiting around the black hole.

### CODE REVIEW

**Comment by PBWiseman** [comment]
Current progress: There is a basic orbit that just spins them all the same speed and orbit around the black hole. I don't love it and want to make elliptical orbits with planet counter rotation, but this isn't a priority and will likely be in another sprint.

The gravity is a work in progress. The player gravity sucks them in to the black hole but I think I want to have it get even stronger as you get closer. It just doesn't quite feel right. The planet gravity (towards the black hole) feels better but it requires the IsKinematic setting on the planets to be toggled which means that the player can move the planets by crashing into them. Will try to find a fix for this.

**Comment by PBWiseman** [comment]
Have an initial gravity and orbiting system. Would love some feedback and reviews. Will be improving the orbiting system at a later date

**Review by 3MKJOE58 — CHANGES_REQUESTED** [review]
I can feel the gravity pulling the ship a little, but it would be better if the gravity was stronger it will give it a more realistic feeling.

**Review by ChaseBENNC9 — CHANGES_REQUESTED** [review]
I like the new gravity system.  Adds a new sense of realism to the game and I think it will give the player more motivation to rescue the planets.   
Code looks good, doesn't give me any errors and seems to run fine.  There's some comments which explain your new code. I do think a small explanation on the add Force method in `BlackHoleGravity.cs` could be useful. Not worried about the maths behind it but more about what the method is doing

All the code works as intended in a build of the game

**Comment by PBWiseman** [comment]
> I can feel the gravity pulling the ship a little, but it would be better if the gravity was stronger it will give it a more realistic feeling.

The issue is that it is really had to have a stronger gravity without it being totally hopeless to get out or dying very fast when the black hole expands. I'll have another play around with the values.

I also have it so that using the booster removes the pull back because otherwise it just wouldn't let you out of the zone when you got in it

**Comment by PBWiseman** [comment]
> I like the new gravity system. Adds a new sense of realism to the game and I think it will give the player more motivation to rescue the planets. Code looks good, doesn't give me any errors and seems to run fine. There's some comments which explain your new code. I do think a small explanation on the add Force method in `BlackHoleGravity.cs` could be useful. Not worried about the maths behind it but more about what the method is doing
> 
> All the code works as intended in a build of the game

Will add more comments

**Review by erokasyuart — CHANGES_REQUESTED** [review]
So from my understanding, the bigger the black hole, the stronger the gravity. One of the first tests I did was turn off the growth script and sit my player ship between the centre of the black hole and the outer and the pull was incredibly weak (at this point the black hole was 20^3), but then on another test I let the black hole grow to about 140^3 and the panic was real, incredibly strong gravity. This paired with the growing black hole works well.

Although, on start, I did not move my player and kept still. I thought it was quite strange that these planet much further away from me were being affected by the black hole but not me! I think it would be more immersive to have another gravity object that is the residual or spacial gravity that is constantly dragging the ship (very weakly! Don't want the player to be constantly in a battle against flying) in the same direction as the planets.

I'll add to this with my UTF results when I figure out how to fix errors it's causing and how to check the gravity with the right assert class :)

**Comment by PBWiseman** [comment]
> So from my understanding, the bigger the black hole, the stronger the gravity. One of the first tests I did was turn off the growth script and sit my player ship between the centre of the black hole and the outer and the pull was incredibly weak (at this point the black hole was 20^3), but then on another test I let the black hole grow to about 140^3 and the panic was real, incredibly strong gravity. This paired with the growing black hole works well.
> 
> Although, on start, I did not move my player and kept still. I thought it was quite strange that these planet much further away from me were being affected by the black hole but not me! I think it would be more immersive to have another gravity object that is the residual or spacial gravity that is constantly dragging the ship (very weakly! Don't want the player to be constantly in a battle against flying) in the same direction as the planets.
> 
> I'll add to this with my UTF results when I figure out how to fix errors it's causing and how to check the gravity with the right assert class :)

By gravity further away do you mean the planets orbiting or being pulled in? The gravity well should be the same area for everyone. The orbits are just hardcoded and aren't actually being touched by the gravity class. I could add a huge zone with a tiny pull but I'm not sure it would be noticed in normal gameplay.

**Comment by erokasyuart** [comment]
> > So from my understanding, the bigger the black hole, the stronger the gravity. One of the first tests I did was turn off the growth script and sit my player ship between the centre of the black hole and the outer and the pull was incredibly weak (at this point the black hole was 20^3), but then on another test I let the black hole grow to about 140^3 and the panic was real, incredibly strong gravity. This paired with the growing black hole works well.
> > Although, on start, I did not move my player and kept still. I thought it was quite strange that these planet much further away from me were being affected by the black hole but not me! I think it would be more immersive to have another gravity object that is the residual or spacial gravity that is constantly dragging the ship (very weakly! Don't want the player to be constantly in a battle against flying) in the same direction as the planets.
> > I'll add to this with my UTF results when I figure out how to fix errors it's causing and how to check the gravity with the right assert class :)
> 
> By gravity further away do you mean the planets orbiting or being pulled in? The gravity well should be the same area for everyone. The orbits are just hardcoded and aren't actually being touched by the gravity class. I could add a huge zone with a tiny pull but I'm not sure it would be noticed in normal gameplay.

Planets are getting pulled by the gravity but not the player in the middle of space. But I agree it wouldn't be noticed in normal gameplay, especially since as soon as the player moves, the residual force makes the ship constantly move anyway.

**Review by ChaseBENNC9 — APPROVED** [review]
I like how you have added some new comments , they are clear and explain the code well. Changes to the black hole are all working, the gravity is definitely more noticeable now and adds a bigger sense of urgency for the player to reach the goal on time.  I believe this is now ready to merge

**Review by erokasyuart — APPROVED** [review]
Works fine, and I like how the planets rotate- that's my favourite part.

**Pull request merged**
