### PR TITLE
CI Reducing Build Time

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
This key will be the same every release and significantly reduces the amount of time that the build and release job takes

## Describe your changes

This is going to significantly reduce the amount of time the building takes when merging into main. It changes the restore key to a specific name rather than creating a random hash which causes it to be unable to find it.

## Issue number and link

#188 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by ChaseBENNC9** [comment]
This is the Build in my fork before the changes
image
and this is the build in my fork after the changes
image

**Comment by ChaseBENNC9** [comment]
this is the hash I was talking about earlier. 
image
The issue was the long hash key changes every time the project went to build so it couldn't find the one that was already there

**Comment by ChaseBENNC9** [comment]
One issue that I know of is this that I don't think if it will affect the next build because the cache does not exist yet.

**Comment by ChaseBENNC9** [comment]
Ready for review.  there isn't much to physically look at but you can see the above screenshots to show the improvements and i will also leave link to the actions if you want to look at the process.
https://github.com/ChaseBENNC9/Space-Rescue/actions/runs/6103371877 here it is with the updated code
https://github.com/ChaseBENNC9/Space-Rescue/actions/runs/5957236603 here it is with the old code
I have also created another workflow that will run on wednesdays and should restore the cache when it expires so it should'nt be gone by the time we go to build. i am currently testing it in m fork

**Review by PBWiseman — APPROVED** [review]
Looks good! Well done on figuring this out. Very impressive

**Review by erokasyuart — APPROVED** [review]
Very impressive stuff! Thank you for optimising this.

**Pull request merged**
