### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by PBWiseman**
Updating the readme to better reflect the current state of the project. Unfinished at the moment. Will be updating further with more information.

### CODE REVIEW

**Comment by PBWiseman** [comment]
Still a work in progress. I have several fields that I want to add commented out.

**Comment by PBWiseman** [comment]
Feel free to add sections or change things if needed. This can be collaborative.

**Comment by PBWiseman** [comment]
Moved to next sprint as this is still a work in progress. This wasn't one of the main issues to be fixed in the sprint and was just a side project as a project leader.

**Comment by PBWiseman** [comment]
Added some more sections. Still needed:

License. Will talk to instructors about appropriate one.
Screenshots and gifs. I have a few videos and I am going to edit them together with the software at polytech computers.
Product description. Still need to write this.

**Comment by PBWiseman** [comment]
Still needs licence information but that can be added when we have one. Ready for review. As I am not good at customer facing wording I have run my original draft through ChatGPT to make it more compelling. Please tell me if it went too far. It does feel a bit like a steam store page pitch and I am unsure if that's a good or bad thing at the moment,

**Review by ChaseBENNC9 — APPROVED** [review]
This branch has significantly improved our documentation. Everything is really well organized and  has lots of detail when needed. I am happy for this to be merged. Excellent job

**Pull request merged**
