### PR TITLE
Better black hole growth

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes

This is responding to a request from our product owner to make the black hole growth feel better by increasing the growth rate in the early game while not making it overwhelming late game. Currently it increases by a % of its current scale so it grows exponentially. I will change this to growing at a consistent rate. Responding to feedback from a user I am also going to be changing the black hole model somewhat and making the center sphere larger.

## Issue number and link

#173 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have written any applicable tests
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by PBWiseman** [comment]
Changed the rate of black hole growth. Would love some reviews on how it feels now.

**Review by ChaseBENNC9 — COMMENTED** [review]
I like your changes; I think the black hole definitely seems more threatening than it was originally, but maybe it needs to be slightly faster?  But I'll see how other reviewers respond to see what overall thoughts are.

It's also hard to know how it will feel before the code is merged because the gravity could affect how it behaves Aswell. 

I didn't notice any bugs while playing, and it's nice to see you fixing some checks to prevent the null exceptions errors.

**Review by erokasyuart — APPROVED** [review]
I like it. Nice slow pace when it gets huge, it really makes a difference.

**Review by ChaseBENNC9 — APPROVED** [review]
With the changes to the gravity I think the values will work well here

**Review by 3MKJOE58 — APPROVED** [review]
like the new black hole, it makes a difference from previous one.

**Pull request merged**
