### PR TITLE
Changing the Ship Boost and Planet Speed

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
## Describe your changes

This Pull Request is going to modify the speed of the ship boosters and the planet orbiting to make navigating to each planet slightly easier.

## Issue number and link

#165 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Comment by ChaseBENNC9** [comment]
Not really requesting proper reviews but I've changed the speed and to account for this increase I've slowed down the recharge rate of the boosters. Can I just have some opinions on whether this still provides a challenge? I haven't touched the orbit speed yet and I will if there is thoughts that that could help balance the game better

**Review by PBWiseman — CHANGES_REQUESTED** [review]
The boost is faster but I think it doesn't really solve the issue that it's just not fun to run out of boost and it isn't really enough to get to planets that aren't the closest one. Plus it doesn't allow you to catch up with planets when you aren't boosting

**Review by 3MKJOE58 — CHANGES_REQUESTED** [review]
the speed is changed, but still when the boost is empty the ship cant catch up to the planets that are rotating away.

**Comment by ChaseBENNC9** [comment]
I've reduced the planet orbiting speed.  The player can now catch up to planets without using the booster.

**Comment by ChaseBENNC9** [comment]
I don't think i can really add any test's to this branch. All my changes come in at play mode not edit mode

**Review by PBWiseman — APPROVED** [review]
Flying feels much better and much more responsive! Happy for this to be approved

**Review by erokasyuart — APPROVED** [review]
This feels smooth and makes the player feel more in control! Good to merge.

**Pull request merged**
