### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by PBWiseman**
Adding some issue templates. Both for the team making bug reports as well as directing people to the discussions tab for feedback. This may not be added to this build. Just something I am working on separately as the team leader.

This is what the style will look like: https://github.com/mobxjs/mobx/issues/new/choose

### CODE REVIEW

**Comment by PBWiseman** [comment]
For PR I am using a workaround to get a menu as shown [here](https://github.com/orgs/community/discussions/4620#discussioncomment-3383383). There are currently only two options, basic and major version

**Comment by PBWiseman** [comment]
I have made a fork to test this with as it needs to be in the main branch of the repo.

To test the issues part click [here](https://github.com/PBWiseman/Space-Rescue/issues). Then click new issue. The bug report button gives you a template with a bug report. There are also links to sections of the Discussions page (note that these link to the real discussions page so please don't create unneeded posts). There is also a option to open a blank issue. I have left this without a template so that it is non obvious and people other than us hopefully won't use it.

To test the pull request part make a new branch, change anything in the file like the readme, and make a new pull request. Ensure that the base repository is set to the PBWiseman/Space-Rescue one. Then click on the preview tab to see the menu. If you click basic template it will make a template using the current base and compare branches. If you click major version it uses a different template with the branches set by default to main and staging.

If you have any feedback or ideas for changes or new templates I'd love to have them. If you need a hand testing it then either comment here or message me on teams

**Comment by ChaseBENNC9** [comment]
you will need to add the team as collaborators for us to be able to open PR's. (unless I missed the email) but the Issue template look great so far.

**Comment by PBWiseman** [comment]
> you will need to add the team as collaborators for us to be able to open PR's. (unless I missed the email) but the Issue template look great so far.

Added

**Review by ChaseBENNC9 — APPROVED** [review]
Issue template looks great, Good detail for the bug report issue as well. The pull request template is also well detailed and should help us make better PR's.

**Review by erokasyuart — APPROVED** [review]
This feels like a professional github repo now

**Review by 3MKJOE58 — APPROVED** [review]

**Pull request merged**
