### PR TITLE
UTF Testing

### PR DESCRIPTION
**Pull request by erokasyuart**
Unit Testing Framework tests code independent from running the game. It uses the assert function to compare expected and actual values to be compared then shows the results in the test runner.

To open the test runner go Window > General > Test Runner. Click all the arrows to expand and see the tests. Click **Run All** to run every test.

To find the test script, go Assets > Tests > Editor > open script files. Every test is it's own method, as shown in the test runner.

I've included two tests to show a true and false result and make sure both were functional.

This uses no assembly definition in the scripts folder because it caused too many conflicts, instead I named the folder "Editor" which is a special folder name in unity and all scripts will automatically be associated with the Assembly-CSharp-Editor.dll assembly, rather than the Assembly-CSharp.dll assembly, as suggested by a commenter in [this](https://www.youtube.com/watch?v=PDYB32qAsLU&ab_channel=InfallibleCode) youtube video.

Please also keep in mind that the gitignore doesn't seem to work and the tests folder will stick to your local computer and then can be pushed onto other branches as soon as you switch to this one. So once you finish testing this branch, delete the Tests folder.

### CODE REVIEW

**Comment by PBWiseman** [comment]
Please add description to this branch as well!

**Comment by PBWiseman** [comment]
Branch still needs a description. Can we also get an update on the progress? Is this going to be ready for this sprint?

**Review by PBWiseman — APPROVED** [review]
Well done on getting this to work with Unity! Very impressive. Obviously we still need to implement the tests but this can come as we are working on features.

**Comment by PBWiseman** [comment]
Also the tests folder doesn't seem to stick to my local computer as long as I have the unity client closed when I swap branches

**Review by ChaseBENNC9 — APPROVED** [review]
test appears to work as intended.
Good use of comments in the testing script to explain the methods. Happy for it to be merged

**Review by 3MKJOE58 — APPROVED** [review]
Test works

**Pull request merged**
