### PR TITLE
New End Screen Menu

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
## Describe your changes

I am adding a new end screen menu to have consistent visuals with the new Main menu and pause menu. 

## Issue number and link

I will be solving issue #133 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] This complies with the [product coding guidelines](https://github.com/BIT-Studio-3/Space-Rescue/wiki/Code-Review-Format)

### CODE REVIEW

**Review by erokasyuart — APPROVED** [review]
Functional and looks good.

**Review by PBWiseman — CHANGES_REQUESTED** [review]
I like the design overall. I think the buttons feel a little off. The Menu and Quit buttons feel a little too far to the outside and spaced away from the restart button and the hover shading feels a little bit too short and hard to click. I had a play around with it and something closer to this felt a bit better personally? 
image
Would be interested in hearing your thoughts and other reviewers on this and if I am alone in this?

**Comment by ChaseBENNC9** [comment]
> I like the design overall. I think the buttons feel a little off. The Menu and Quit buttons feel a little too far to the outside and spaced away from the restart button and the hover shading feels a little bit too short and hard to click. I had a play around with it and something closer to this felt a bit better personally? image Would be interested in hearing your thoughts and other reviewers on this and if I am alone in this?

I've made the hitboxes a bit larger and moved them in line similar to what you have here

**Review by PBWiseman — APPROVED** [review]
I like the changes and am happy for this to be merged!

**Review by 3MKJOE58 — APPROVED** [review]

**Pull request merged**
